name: Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: gha-test

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ISSUE_LABEL: gha-test
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Configure direnv
        uses: HatsuneMiku3939/direnv-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - run: npm ci
      - run: npm test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
